---
title: "Meeting 2"
author: "Rui Li"
date: "10/2/2020"
header-includes:
- \usepackage{amsgen,amsmath,amstext,amsbsy,amsopn,amssymb,mathabx,amsthm,bm,bbm}
- \usepackage[labelsep=space]{caption}
output:
  word_document: default
  html_document: default
subtitle: $\textbf{STOR 691H, FALL 2020}$
---

# Require packages
```{r message = False}
library(utils)
library(dplyr)
library(ggplot2)
library(maps)
library(stringr)
```

# Import the newest COVID-19 Dataset 
```{r}
#these libraries need to be installed
#library(utils)

#read the Dataset sheet into “R”. The dataset will be called "data".
data <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
```

# Data cleaning and Summary
```{r}
#library("dplyr") require "dplyr" package for the use of %>%
covid.data = data %>%
              rename(Date="dateRep") %>%
              rename(Region="countriesAndTerritories") %>%
              mutate(Date=as.Date(Date,format="%d/%m/%y"))%>% 
              mutate(Region = str_replace_all(Region, "_", " "))

summary(covid.data)
head(covid.data)
```

```{r}
#Unmatch Area
worldData = map_data("world")
regions = unique(covid.data$Region)
region_w = unique(worldData$region)

missing_region = c()
for (i in 1:length(regions)) {
  if(!regions[i]%in%region_w){
    missing_region = c(regions[i],missing_region)
  }
}
missing_region = as.data.frame(missing_region); names(missing_region) = c("Missing Region")
world_region = as.data.frame(region_w); names(world_region) = c("World Region")
```

```{r}
#population dataframe
pop.data = unique(data.frame(covid.data$Region,covid.data$popData2019,covid.data$continentExp,covid.data$countryterritoryCode))

names(pop.data)=c("Region","Population2019","Continents","Codes")

pop.data = na.omit(pop.data)
```

```{r message=FALSE}
#Population
#Exchange darke and light
library(plotly)

pop.fig <- plot_ly(pop.data, type='choropleth', locations=pop.data$Codes, z=log(pop.data$Population2019), text=pop.data$Region, colorscale="Blues")

pop.fig
```

```{r message=False}
#Square Miles
library(readr)
area <- read_csv("Squares Miles 2013.csv")

#Check missing
for (i in 1:length(regions)) {
  if(!regions[i]%in%area$Country){
    print(regions[i])
  }
}
```

```{r}
#Case/death Ratio
#cases dataframe
case.data = data.frame(covid.data$Region,covid.data$cases,covid.data$countryterritoryCode) 
names(case.data) = c("Region","cases","Codes") 
case.data=aggregate(case.data$cases, by=list(Category=case.data$Region), FUN=sum)
case.data = as.data.frame(cbind(case.data,unique(covid.data$countryterritoryCode)))
names(case.data) = c("Region","cases","Codes")
case.data = na.omit(case.data)

#death dataframe
death.data = data.frame(covid.data$Region,covid.data$deaths,covid.data$countryterritoryCode) 
names(death.data) = c("Region","deaths","Codes") 
death.data=aggregate(death.data$deaths, by=list(Category=death.data$Region), FUN=sum)
death.data = as.data.frame(cbind(death.data,unique(covid.data$countryterritoryCode)))
names(death.data) = c("Region","deaths","Codes")
death.data = na.omit(death.data)

#Case/death dataframe
case_death.data = data.frame(case.data$Region,death.data$deaths/case.data$cases,case.data$Codes)
names(case_death.data) = c("Region","Case/Deaths Ratio","Codes")
```

```{r}
case.fig <- plot_ly(case.data, type='choropleth', locations=case.data$Codes, z=log(case.data$cases), text=case.data$Region, colorscale="Blues")

case.fig
```

```{r}
death.fig <- plot_ly(death.data, type='choropleth', locations=death.data$Codes, z=log(death.data$deaths+1), text=case.data$Region, colorscale="Blues")

death.fig
```

```{r}
#case_death.data <- case_death.data[is.finite(case_death.data$`Case/Deaths Ratio`),]
case_death.fig <- plot_ly(case_death.data, type='choropleth', locations=case_death.data$Codes, z=case_death.data$`Case/Deaths Ratio`, text=case_death.data$Region, colorscale="Blues")

case_death.fig
```

```{r}
#death/pop *100
death_pop.data = data.frame(pop.data$Region,death.data$deaths/pop.data$Population2019*100,pop.data$Codes)
names(death_pop.data) = c("Region","Values","Codes")

death_pop.fig <- plot_ly(death_pop.data, type='choropleth', locations=death_pop.data$Codes, z=death_pop.data$`Values`, text=death_pop.data$Region, colorscale="Blues")

death_pop.fig
```

```{r}
library(tidyverse)
combine = full_join(pop.data,area, by=c("Region"="Country"))
```
#Square miles join
#Hospitals Prediction
#https://lme4.r-forge.r-project.org/book/Ch4.pdf

#https://www.r-graph-gallery.com/animation.html
#https://www.r-graph-gallery.com/animation.html
#https://d4tagirl.com/2017/05/how-to-plot-animated-maps-with-gganimate
#https://plotly-r.com/animating-views.html

#Date Variable
#Change cases each country
